modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "compressedbox"
version = "${version}"
displayName = "Compressed Box"
authors = "iglee42"
description = '''
Create compressed boxes to gain space in your bases
'''
logoFile = "logo.png"

[[dependencies.compressedbox]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.compressedbox]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.compressedbox]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "compressedbox.mixins.json"
